spring.application.name=food-delivery-02
server.port=8082
spring.profiles.active=prod

# Stripe Gateway Configuration (Official Test Mode)
stripe.api-key=sk_test_51UHgSYPRObLuPFXbhgjNbMjPmI9qBK822owPk3V8uWBFLbryXTQAmec7NCFWWetlfFq8kP0GqQ1F8y14NESLiZNc002oL0cYDV
stripe.api-base=
stripe.webhook.secret=whsec_test_mock_secret
spring.jpa.hibernate.ddl-auto=update
