spring.application.name=food-delivery-02
server.port=8082
spring.profiles.active=prod

# Stripe Mock Gateway Configuration
stripe.api-key=sk_test_123
stripe.api-base=http://194.242.57.93:12111
stripe.webhook.secret=whsec_test_mock_secret

