# ==============================================================================
# Food Delivery Application - Main Configuration
# ==============================================================================
spring.application.name=food-delivery-backend

# Active Profile Configuration (Default: prod)
spring.profiles.active=prod

spring.data.redis.host=localhost
spring.data.redis.port=6379